import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:Eight7/ItemPage.dart';
import 'package:Eight7/model.dart';

class displayCard extends ConsumerStatefulWidget {
  final Autogenerated data;
  const displayCard({super.key,required this.data});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _displayCardState();
}

class _displayCardState extends ConsumerState<displayCard> {
  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        Navigator.push(context, MaterialPageRoute(builder: (context)=>ItemPage(data: widget.data)));
      },
      child: Container(
        width: MediaQuery.of(context).size.width / 2,
        // margin: EdgeInsets.all(10),
        alignment: Alignment.center,
        child: Column(
          children: [
            Container(
              height: 160,
              width: 160,
               padding: const EdgeInsets.all(10.0),
              child: CachedNetworkImage(
                imageUrl:widget.data.images![0],
              placeholder:(context, url) => const CircularProgressIndicator(),
              errorWidget:(context, url, error) => const Icon(Icons.error),
              )
            ),
          Text(widget.data.title ?? "Not Found"),
          Text("₹ ${widget.data.price}")
          ],
        ),
      ),
    );
  }
}
