

import 'package:dio/dio.dart';
import 'package:Eight7/model.dart';

Future<List<Autogenerated>> getProducts(int index) async {
  final Dio dio = Dio();
  var response = await dio
      .get("https://api.escuelajs.co/api/v1/categories/$index/products");
  
    return (response.data as List).map((e) => Autogenerated.fromJson(e)).toList();
  

}
