import 'package:cached_network_image/cached_network_image.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:Eight7/model.dart';

class ItemPage extends ConsumerWidget {
  final Autogenerated data;
  const ItemPage({super.key,required this.data});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0,
       backgroundColor: Colors.black,
      ),
      body: Column(children: [
        CarouselSlider(
        options: CarouselOptions(),
        items: data.images?.map((e) => Center(
          child: CachedNetworkImage(imageUrl: e,fit: BoxFit.cover, width: 1000,
           placeholder:(context, url) => const CircularProgressIndicator(),
            errorWidget:(context, url, error) => const Icon(Icons.error),
          ),
        )).toList(),
        ),
        Container(
          margin: const EdgeInsets.all(20),
          alignment: Alignment.centerLeft,
          child: Text(data.title ?? "Unknown",style: const TextStyle(fontSize: 20,fontWeight: FontWeight.bold),),),
          Container(
          margin: const EdgeInsets.only(left:20),
          alignment: Alignment.centerLeft,
          child: Text("₹ ${data.price}",style: const TextStyle(fontSize: 18,fontWeight: FontWeight.w500),),),
          Container(
          margin: const EdgeInsets.all(20),
          alignment: Alignment.centerLeft,
          child: Text("${data.description}",style: const TextStyle(fontSize: 15,fontWeight: FontWeight.w400,color: Colors.black54),),)
          
        ],),
    );
  }
}
